apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    template: postgresql-persistent-template
  name: postgresql
spec:
  accessModes:
  - ReadWritesOnce
  resources:
    requests:
      storage: 2Gi
